apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "{{NAME}}"
  namespace: "{{NAMESPACE}}"
spec:
  source:
    http:
      url: "{{IMAGE_URL}}"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: "{{STORAGE}}Gi"
