apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lab-vm-secure-policy
  namespace: "{{NAMESPACE}}"
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress

  ingress: []

  egress:
    # Cho phép DNS
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

    # Cho phép tất cả traffic ra Internet (bao gồm ICMP, HTTP, HTTPS)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
              - 169.254.0.0/16
              - 127.0.0.0/8
