apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{NAME}}"
  namespace: "{{NAMESPACE}}"
spec:
  storageClassName: "{{BACKING_IMAGE}}"
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: "{{STORAGE}}Gi"
