apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{NAME}}"
  namespace: "{{NAMESPACE}}"
spec:
  storageClassName: longhorn-ext4-backing
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: "{{STORAGE}}"